### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by jayvdb** [morlandi/djtest#1]
Nice concept.

Do you plan to put it on PyPI soon?  https://pypi.org/project/djtest is available ...

**Comment by morlandi** [comment]
Thank you @jayvdb 
This little script was meant for personal use, but since you're expressing an interest in it I will be very pleased to publish it on PyPI ... I'll do it next week since now I'm abroad with my family.

Do you have any suggestion for a package name better that "djtest" ?

**Comment by jayvdb** [comment]
`djtest` is fine, and requires no extra fiddling with the source, repo name, etc.

`djitest` maybe, for 'interactive'?

**Comment by morlandi** [comment]
hello @jayvdb 
I just published djtest on PyPI.
`djitest` was nice, but I finally decided to keep the original name for laziness ;)
